# Site settings
author: Steve Albonico
title: Coding, Drinking, Traveling
header-img: img/home-bg.png
email: salbonico@gmail.com
copyright_name: Steve Albonico
description: > # this means to ignore newlines until "baseurl:"
  There is no permanent record.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  salbonico

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
